name: Final Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start virtual display
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "Xvfb started"

      - name: Run Cypress E2E Test (with Chrome headed)
        run: |
          npx cypress run --browser chrome --headed \
            --config video=true \
            --env grepTags=@smoke
        env:
          DISPLAY: :99
          CYPRESS_baseUrl: https://www.agoda.com

      - name: Upload screenshots if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
